name: ESLint

on:
  pull_request:
    branches: [master]
    paths:
      - "**.js"
      - readme.md
      - package.json
      - .github/workflows/eslint.yml
  push:
    branches: [master]
    paths:
      - "**.js"
      - readme.md
      - package.json
      - .github/workflows/eslint.yml

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run eslint
